#pythoncode


#B1022 changes
<!DOCTYPE html>
<html>
<head>
    <title>Button Example</title>
</head>
<body>
    <button onclick="alert('Hello!')">Click Me</button>
</body>
</html>
#B1022 Ends

#B1021changes
<!DOCTYPE html>
<html>
<head>
    <title>Link Example</title>
</head>
<body>
    <a href="https://www.example.com">Visit Example</a>
</body>
</html>

#B1021 ends
<html>
<body>
<h5> Jenkins</h5>
</body>
</html>
